CREATE DATABASE QLBanVeXeKhach
GO

USE QLBanVeXeKhach
GO

CREATE TABLE QUYEN
(
	ID_Quyen INT,
	TenQuyen NVARCHAR(100),
	CONSTRAINT PK_ID_Quyen PRIMARY KEY(ID_Quyen)
)
GO

CREATE TABLE TAIKHOAN
(
	ID_TaiKhoan INT,
	TenTaiKhoan VARCHAR(30),
	MatKhau VARCHAR(50),
	HoTen NVARCHAR(100),
	NgaySinh DATE,
	DiaChi NVARCHAR(100),
	SoDT CHAR(10),
	Email CHAR(50),
	ID_Quyen INT,
	CONSTRAINT PK_ID_TaiKhoan PRIMARY KEY(ID_TaiKhoan),
	CONSTRAINT FK_ID_Quyen_TaiKhoan FOREIGN KEY(ID_Quyen) REFERENCES dbo.QUYEN
)
GO

CREATE TABLE PHUONGTHUCTHANHTOAN
(
	ID_PTTT INT,
	TenPTTT NVARCHAR(100),
	NoiDungPTTT NVARCHAR(100),
	CONSTRAINT PK_ID_PTTT PRIMARY KEY(ID_PTTT)
)
GO

CREATE TABLE HANGXE
(
	ID_HangXe INT,
	TenHangXe NVARCHAR(100),
	LogoHangXe VARCHAR(100),
	ThongTinHangXe NVARCHAR(1000),
	CONSTRAINT PK_ID_HangXe PRIMARY KEY(ID_HangXe)
)
GO

CREATE TABLE XEKHACH
(
	ID_XeKhach VARCHAR(20),
	HinhAnhXe VARCHAR(100),
	SoGhe INT,
	MoTa NVARCHAR(200),
	ID_HangXe INT,
	CONSTRAINT PK_ID_XeKhach PRIMARY KEY(ID_XeKhach),
	CONSTRAINT FK_ID_HangXe FOREIGN KEY(ID_HangXe) REFERENCES dbo.HANGXE(ID_HangXe)
)
GO

CREATE TABLE DIEMDEN
(
	ID_DiemDen INT,
	TenDiemDen NVARCHAR(100),
	CONSTRAINT PK_DiemDen PRIMARY KEY(ID_DiemDen)
)
GO

CREATE TABLE DIEMXUATPHAT
(
	ID_DiemXP INT,
	TenDiemXP NVARCHAR(100),
	CONSTRAINT PK_DiemXP PRIMARY KEY(ID_DiemXP)
)
GO

CREATE TABLE CHUYENXE
(
	ID_ChuyenXe INT,
	ID_DiemDen INT,
	ID_DiemXP INT,
	ThoiGianXP DATETIME,
	ThoiGianDen DATETIME,
	SoGheTrong INT,
	GiaVe FLOAT,
	ID_XeKhach VARCHAR(20),
	CONSTRAINT PK_ID_ChuyenXe PRIMARY KEY(ID_ChuyenXe),
	CONSTRAINT FK_ID_XeKhach FOREIGN KEY(ID_XeKhach) REFERENCES dbo.XEKHACH(ID_XeKhach)
)
GO

CREATE TABLE THONGTINDATVE
(
	ID_ThongTinDatVe INT,
	ThoiGianDatVe DATETIME,
	SoLuongVe INT,
	LyDoHuyVe NVARCHAR(100),
	TrangThaiDatVe NVARCHAR(100),
	ID_ChuyenXe INT,
	ID_TaiKhoan INT,
	ID_PTTT INT,
	CONSTRAINT PK_ID_ThongTinDatVe PRIMARY KEY(ID_ThongTinDatVe),
	CONSTRAINT FK_ID_ChuyenXe FOREIGN KEY(ID_ChuyenXe) REFERENCES dbo.CHUYENXE(ID_ChuyenXe),
	CONSTRAINT FK_ID_TaiKhoan FOREIGN KEY(ID_TaiKhoan) REFERENCES dbo.TAIKHOAN(ID_TaiKhoan),
	CONSTRAINT FK_ID_PTTT FOREIGN KEY(ID_PTTT) REFERENCES dbo.PHUONGTHUCTHANHTOAN(ID_PTTT)
)
GO